### ISSUE TITLE
[Feat] 파이어베이스 세팅 및 Authenticaion 기능 구현

### ISSUE THREAD

**Issue by L-j-h-c** [L-j-h-c/MVVM-of-JunHo#4]
## 📌  Issue

파이어베이스 세팅 및 Authenticaion 기능 구현

## 📝  To-do

- [ ] 파이어베이스 세팅
- [ ] CocoaPod Bug Fix
- [ ] 파이어베이스에 유저 등록
- [ ] Authenticaion 기능 구현
