### ISSUE TITLE
[Feat] 파이어스토어에서 유저 데이터 받아오고 표시하기

### ISSUE THREAD

**Issue by L-j-h-c** [L-j-h-c/MVVM-of-JunHo#7]
## 📌  Issue

파이어스토어에서 유저 데이터 받아오고 표시하기

## 📝  To-do

- [x] 데이터 모델 생성 및 유저데이터 받아오기
- [x] 프로필 헤더 뷰 모델 작성
- [x] 유저 인증 이후 업데이트
- [x] 서치 컨트롤러 UI
- [x] 유저 받아오고 페치하기
- [x] 유저 검색하기
